on:
  push:
    tags:
      - '*'
 
name: tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems2-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems2-

    - name: list vendor/bundle directory
      run: find vendor/bundle
      continue-on-error: true

    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle check || bundle install --jobs 4 --retry 3
        bundle package
    - name: list vendor/bundle directory
      run: find vendor/bundle
      continue-on-error: true
