on: [push, pull_request]
name: tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: list vendor/bundle directory
      run: find vendor/bundle

    - name: bundle install
      run: |
        gem install bundle
        bundle update --bundler
        bundle install --jobs 4 --retry 3 --path 'vendor/bundle'

    - name: list vendor/bundle directory
      run: find vendor/bundle

